### PR TITLE
to fix the format option issue

### PR DESCRIPTION
**Pull request by showjason**
#773 
I see the subcommand `format` supports multiple secret key-like options whose value will contain `=` most likely, therefore I try to use `SplitN` to split the options to fixed length 2, so that the `=` in the value can be ignored. If it's not reasonable, please let me know

### CODE REVIEW

**Comment by zwwhdls** [comment]
Hi @showjason , please fix the unit test. thx!

**Comment by showjason** [comment]
> Hi @showjason , please fix the unit test. thx!

Ah...sorry, I missed some particular cases, let me fix.

**Comment by zwwhdls** [comment]
@Hexilee PTAL

**Review by Hexilee — APPROVED** [review]

**Pull request merged**
