### PR TITLE
enable apiserver list cache by environment variable

### PR DESCRIPTION
**Pull request by xing0821**
add environment variable 'ENABLE_APISERVER_LIST_CACHE' for enable apiserver list cache

### CODE REVIEW

**Comment by zwwhdls** [comment]
Can you add some comments in code to explain why resourceVersion=0 means ? @xing0821

**Comment by xing0821** [comment]
> Can you add some comments in code to explain why resourceVersion=0 means ? @xing0821

sure, add some comments for resourceVersion

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by zwwhdls — APPROVED** [review]

**Comment by zwwhdls** [comment]
@xing0821 , thanks for your contribution!

**Pull request merged**
