### PR TITLE
Support to retain the volume if Delete reclaim policy

### PR DESCRIPTION
**Pull request by kyungwan-nam**
PR for https://github.com/juicedata/juicefs-csi-driver/issues/1015

### CODE REVIEW

**Comment by zwwhdls** [comment]
It seems strange to retain volume in delete reclaim policy. I don't want to support such a feature, which violates the reclaim semantics of PV. What do you think? cc @zxh326

**Comment by zxh326** [comment]
we don't want to support this feature because it violates the design of CSI

thx..i will close this PR

**Comment by kyungwan-nam** [comment]
Thank you for reviewing it.
I got it. I can handle it in another way.
Thanks.

**Comment by tsic404** [comment]
> Thank you for reviewing it. I got it. I can handle it in another way. Thanks.

How did you deal with this in the end?

**Pull request closed without merging**
